export const SET_TITLE = 'SET_TITLE'

export const SET_WARNS_BASE = 'SET_WARNS_BASE'

export const SET_WARNS_CACHE = 'SET_WARNS_CACHE'

export const SET_WARNS_REPLICATION = 'SET_WARNS_REPLICATION'

export const SET_BASE_DATA = 'SET_BASE_DATA'

export const SET_CACHE_DATA = 'SET_CACHE_DATA'

export const SET_REPLICATION_DATA = 'SET_REPLICATION_DATA'